2025-04-18 10:59:15,051 - [Rank0] #################################################################
2025-04-18 10:59:15,052 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:59:15,131 - [Rank0] User network built successfully.
2025-04-18 11:03:53,057 - [Rank0] ERROR: !stack.empty() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/autograd/profiler_python.cpp":983, please report a bug to PyTorch. Python replay stack is empty.
2025-04-18 13:47:59,316 - [Rank0] #################################################################
2025-04-18 13:47:59,316 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:47:59,425 - [Rank0] User network built successfully.
2025-04-18 13:48:23,176 - [Rank0] #################################################################
2025-04-18 13:48:23,177 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:48:59,134 - [Rank0] #################################################################
2025-04-18 13:48:59,135 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:51:47,035 - [Rank0] #################################################################
2025-04-18 13:51:47,035 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:51:47,121 - [Rank0] User network built successfully.
2025-04-18 13:52:50,836 - [Rank0] #################################################################
2025-04-18 13:52:50,836 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:52:50,924 - [Rank0] User network built successfully.
2025-04-18 13:53:26,803 - [Rank0] #################################################################
2025-04-18 13:53:26,803 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:53:26,906 - [Rank0] User network built successfully.
2025-04-18 13:53:58,892 - [Rank0] #################################################################
2025-04-18 13:53:58,892 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:53:58,970 - [Rank0] User network built successfully.
2025-04-18 13:54:34,666 - [Rank0] #################################################################
2025-04-18 13:54:34,666 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:54:34,761 - [Rank0] User network built successfully.
2025-04-18 13:55:41,656 - [Rank0] #################################################################
2025-04-18 13:55:41,657 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:55:41,755 - [Rank0] User network built successfully.
2025-04-18 13:56:09,796 - [Rank0] #################################################################
2025-04-18 13:56:09,798 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:56:09,908 - [Rank0] User network built successfully.
2025-04-18 13:58:44,530 - [Rank0] #################################################################
2025-04-18 13:58:44,531 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:58:44,626 - [Rank0] User network built successfully.
2025-04-18 13:59:13,371 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-18 13:59:13,373 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 979, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 75, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 76, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 456, in _process
    self._propagate()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 466, in _propagate
    self.pos.inject_currents(self._current_buffer)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 600, in inject_currents
    t_mod = SimulatorEngine.engine.local_circuit.t % self.n_bridge_steps
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
RuntimeError: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_01_multipleGPUs.py", line 67, in <module>
    with PingPongRingSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 897, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 978, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/edlut/lib/python3.12/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/edlut/lib/python3.12/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-18 14:00:15,483 - [Rank0] #################################################################
2025-04-18 14:00:15,484 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:00:15,565 - [Rank0] User network built successfully.
2025-04-18 14:00:29,923 - [Rank0] #################################################################
2025-04-18 14:00:29,924 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:00:30,009 - [Rank0] User network built successfully.
2025-04-18 14:00:44,321 - [Rank0] #################################################################
2025-04-18 14:00:44,321 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:00:44,406 - [Rank0] User network built successfully.
2025-04-18 14:02:04,975 - [Rank0] #################################################################
2025-04-18 14:02:04,976 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:02:05,056 - [Rank0] User network built successfully.
2025-04-18 14:04:56,093 - [Rank0] #################################################################
2025-04-18 14:04:56,094 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:04:56,191 - [Rank0] User network built successfully.
2025-04-18 14:09:45,289 - [Rank0] #################################################################
2025-04-18 14:09:45,290 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:09:45,366 - [Rank0] User network built successfully.
2025-04-18 14:09:45,879 - [Rank0] ERROR: output with shape [1000, 1] doesn't match the broadcast shape [1000, 1000]
2025-04-18 14:09:45,881 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_01_multipleGPUs.py", line 71, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 997, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 75, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 75, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 76, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 456, in _process
    self._propagate()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 468, in _propagate
    self.pos.inject_currents(self._current_buffer)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 611, in inject_currents
    self.write_buffer[:, t_mod] |= mask # In-place bitwise OR
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: output with shape [1000, 1] doesn't match the broadcast shape [1000, 1000]

2025-04-18 14:10:30,403 - [Rank0] #################################################################
2025-04-18 14:10:30,404 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:10:30,493 - [Rank0] User network built successfully.
2025-04-18 14:11:56,209 - [Rank0] ERROR: output with shape [1000, 1] doesn't match the broadcast shape [1000, 1000]
2025-04-18 14:11:56,211 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_01_multipleGPUs.py", line 71, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 997, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 75, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 75, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 76, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 456, in _process
    self._propagate()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 468, in _propagate
    self.pos.inject_currents(self._current_buffer)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/all.py", line 611, in inject_currents
    self.write_buffer[:, t_mod] |= mask # In-place bitwise OR
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: output with shape [1000, 1] doesn't match the broadcast shape [1000, 1000]

2025-04-18 14:13:15,271 - [Rank0] #################################################################
2025-04-18 14:13:15,273 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:13:15,380 - [Rank0] User network built successfully.
2025-04-18 14:13:37,095 - [Rank0] #################################################################
2025-04-18 14:13:37,095 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:13:37,167 - [Rank0] User network built successfully.
2025-04-19 09:26:05,927 - [Rank0] #################################################################
2025-04-19 09:26:05,927 - [Rank0] Neurobridge initialized. Building user network...
2025-04-19 09:26:05,997 - [Rank0] User network built successfully.
2025-04-19 11:28:46,145 - [Rank0] #################################################################
2025-04-19 11:28:46,145 - [Rank0] Neurobridge initialized. Building user network...
2025-04-19 11:28:46,225 - [Rank0] User network built successfully.
2025-04-19 11:29:08,566 - [Rank0] #################################################################
2025-04-19 11:29:08,567 - [Rank0] Neurobridge initialized. Building user network...
2025-04-19 11:29:08,676 - [Rank0] User network built successfully.
